#ifndef SMART_LOGISTICS_CONFIG_H
#define SMART_LOGISTICS_CONFIG_H

#define SL_WIFI_SSID "<WIFI_SSID>"
#define SL_WIFI_PASSWORD "<WIFI_PASSWORD>"
#define SL_MQTT_HOST "<MQTT_HOST>"
#define SL_MQTT_PORT 1883
#define SL_MQTT_USERNAME "<MQTT_USERNAME>"
#define SL_MQTT_PASSWORD "<MQTT_PASSWORD>"
#define SL_VEHICLE_ID "sim_999"

#endif
