<script setup>
import { computed,onMounted,reactive,ref } from 'vue'
import { ElMessage,ElMessageBox } from 'element-plus'
import PageHeader from '../components/PageHeader.vue'
import { api,extractList } from '../api/http'
const rows=ref([]),loading=ref(false),keyword=ref(''),dialogVisible=ref(false)
const form=reactive({cargoNo:'',name:'',ownerName:'',weight:null,volume:null,status:'WAITING'})
const statusText={WAITING:'待运输',TRANSPORTING:'运输中',COMPLETED:'已完成',ABNORMAL:'异常'}
const normalize=c=>({...c,id:c.id??c.cargoId??c.cargo_id,cargoNo:c.cargoNo??c.cargo_no??'-',ownerName:c.ownerName??c.owner_name??c.owner?.name??'-',weight:c.weight??'-',volume:c.volume??'-',status:c.status??'WAITING'})
const list=computed(()=>rows.value.filter(c=>!keyword.value||[c.name,c.cargoNo,c.ownerName].some(x=>String(x||'').toLowerCase().includes(keyword.value.toLowerCase()))))
async function load(){loading.value=true;try{rows.value=extractList(await api.cargos.list()).map(normalize)}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
function openCreate(){Object.assign(form,{cargoNo:'',name:'',ownerName:'',weight:null,volume:null,status:'WAITING'});dialogVisible.value=true}
async function save(){if(!form.name)return ElMessage.warning('请填写货物名称');try{await api.cargos.create({...form});ElMessage.success('货物新增成功');dialogVisible.value=false;await load()}catch(e){ElMessage.error(e.message)}}
async function detail(row){try{const c=normalize(await api.cargos.get(row.id));await ElMessageBox.alert(`货物编号：${c.cargoNo}<br>货主：${c.ownerName}<br>重量：${c.weight} kg<br>体积：${c.volume} m³<br>状态：${statusText[c.status]||c.status}`,c.name,{dangerouslyUseHTMLString:true})}catch(e){ElMessage.error(e.message)}}
onMounted(load)
</script>
<template><PageHeader title="货物管理" subtitle="数据来自云端货物 API"/><section class="panel page-panel"><div class="toolbar"><el-input v-model="keyword" clearable placeholder="搜索货物编号/名称/货主" style="width:280px"/><el-button @click="load">刷新</el-button><el-button type="primary" @click="openCreate">+ 新增货物</el-button></div><el-table v-loading="loading" :data="list" stripe empty-text="暂无货物数据"><el-table-column prop="cargoNo" label="货物编号" min-width="150"/><el-table-column prop="name" label="名称"/><el-table-column prop="ownerName" label="货主"/><el-table-column prop="weight" label="重量(kg)"/><el-table-column prop="volume" label="体积(m³)"/><el-table-column label="状态"><template #default="s"><el-tag>{{statusText[s.row.status]||s.row.status}}</el-tag></template></el-table-column><el-table-column label="操作"><template #default="s"><el-button link type="primary" @click="detail(s.row)">详情</el-button></template></el-table-column></el-table></section><el-dialog v-model="dialogVisible" title="新增货物" width="520px"><el-form label-width="90px"><el-form-item label="货物编号"><el-input v-model="form.cargoNo"/></el-form-item><el-form-item label="名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="货主"><el-input v-model="form.ownerName"/></el-form-item><el-form-item label="重量(kg)"><el-input-number v-model="form.weight" :min="0" style="width:100%"/></el-form-item><el-form-item label="体积(m³)"><el-input-number v-model="form.volume" :min="0" :precision="2" style="width:100%"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status" style="width:100%"><el-option v-for="(label,value) in statusText" :key="value" :label="label" :value="value"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></template>
