<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../components/PageHeader.vue'
import { api, extractList } from '../api/http'
const loading=ref(false), rows=ref([]), keyword=ref(''), status=ref(''), dialogVisible=ref(false), editingId=ref(null)
const form=reactive({plateNumber:'',type:'',capacity:null,status:'IDLE',driverName:''})
const statusText={IDLE:'空闲',TRANSPORTING:'运输中',MAINTENANCE:'维修',DISABLED:'停用'}
const normalize=v=>({...v,vehicleId:v.vehicleId??v.vehicle_id??v.id,plateNumber:v.plateNumber??v.plate_number??v.licensePlate??v.license_plate??'-',driverName:v.driverName??v.driver_name??v.driver?.name??'-',type:v.type??v.vehicleType??v.vehicle_type??'-',capacity:v.capacity??v.loadCapacity??v.load_capacity??'-',status:v.status??'IDLE'})
const list=computed(()=>rows.value.filter(v=>{const w=keyword.value.trim().toLowerCase();return(!w||[v.plateNumber,v.driverName,v.type].some(x=>String(x||'').toLowerCase().includes(w)))&&(!status.value||v.status===status.value)}))
async function load(){loading.value=true;try{rows.value=extractList(await api.vehicles.list({status:status.value})).map(normalize)}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
function openCreate(){editingId.value=null;Object.assign(form,{plateNumber:'',type:'',capacity:null,status:'IDLE',driverName:''});dialogVisible.value=true}
function openEdit(v){editingId.value=v.vehicleId;Object.assign(form,v);dialogVisible.value=true}
async function save(){if(!form.plateNumber||!form.type)return ElMessage.warning('请填写车牌号和车型');try{editingId.value?await api.vehicles.update(editingId.value,{...form}):await api.vehicles.create({...form});ElMessage.success(editingId.value?'车辆修改成功':'车辆新增成功');dialogVisible.value=false;await load()}catch(e){ElMessage.error(e.message)}}
async function detail(row){try{const v=normalize(await api.vehicles.get(row.vehicleId));await ElMessageBox.alert(`车型：${v.type}<br>载重：${v.capacity} kg<br>司机：${v.driverName}<br>状态：${statusText[v.status]||v.status}`,`${v.plateNumber} · 车辆详情`,{dangerouslyUseHTMLString:true})}catch(e){ElMessage.error(e.message)}}
async function remove(row){try{await ElMessageBox.confirm(`确定停用/删除车辆 ${row.plateNumber} 吗？`,'操作确认',{type:'warning'});await api.vehicles.remove(row.vehicleId);ElMessage.success('操作成功');await load()}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message||'操作失败')}}
onMounted(load)
</script>
<template><PageHeader title="车辆管理" subtitle="数据来自云端车辆 API"/><section class="panel page-panel"><div class="toolbar"><el-input v-model="keyword" clearable placeholder="搜索车牌、司机或车型" style="width:240px"/><el-select v-model="status" placeholder="全部状态" clearable style="width:150px" @change="load"><el-option v-for="(label,value) in statusText" :key="value" :label="label" :value="value"/></el-select><el-button @click="load">刷新</el-button><el-button type="primary" @click="openCreate">+ 新增车辆</el-button></div><el-table v-loading="loading" :data="list" stripe empty-text="暂无车辆数据"><el-table-column prop="plateNumber" label="车牌" min-width="120"/><el-table-column prop="type" label="车型"/><el-table-column prop="capacity" label="载重(kg)"/><el-table-column prop="driverName" label="所属司机"/><el-table-column label="状态"><template #default="s"><el-tag>{{statusText[s.row.status]||s.row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="210"><template #default="s"><el-button link type="primary" @click="detail(s.row)">详情</el-button><el-button link type="primary" @click="openEdit(s.row)">编辑</el-button><el-button link type="danger" @click="remove(s.row)">停用/删除</el-button></template></el-table-column></el-table></section><el-dialog v-model="dialogVisible" :title="editingId?'修改车辆':'新增车辆'" width="520px"><el-form label-width="90px"><el-form-item label="车牌号" required><el-input v-model="form.plateNumber"/></el-form-item><el-form-item label="车型" required><el-input v-model="form.type"/></el-form-item><el-form-item label="载重(kg)"><el-input-number v-model="form.capacity" :min="0" style="width:100%"/></el-form-item><el-form-item label="司机"><el-input v-model="form.driverName"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status" style="width:100%"><el-option v-for="(label,value) in statusText" :key="value" :label="label" :value="value"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></template>
