# Copyright (c) 2026
# Licensed under the Apache License, Version 2.0.

static_library("gps_uart_test") {
    sources = [
        "gps_uart_test.c",
        "../D13_iot_cloud_oc_gps/src/E53_ST1.c",
    ]

    include_dirs = [
        "//utils/native/lite/include",
        "//kernel/liteos_m/components/cmsis/2.0",
        "//base/iot_hardware/interfaces/kits/wifiiot_lite",
        "../D13_iot_cloud_oc_gps/include",
    ]
}
